//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusOperationsClient_991396063.DBOperationServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusInfo", Namespace="http://schemas.datacontract.org/2004/07/FinalBusService_991396063")]
    [System.SerializableAttribute()]
    public partial class BusInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BusIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MakeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BusId {
            get {
                return this.BusIdField;
            }
            set {
                if ((this.BusIdField.Equals(value) != true)) {
                    this.BusIdField = value;
                    this.RaisePropertyChanged("BusId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Make {
            get {
                return this.MakeField;
            }
            set {
                if ((object.ReferenceEquals(this.MakeField, value) != true)) {
                    this.MakeField = value;
                    this.RaisePropertyChanged("Make");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DBOperationServiceReference.DBOperationsService")]
    public interface DBOperationsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBOperationsService/InsertABus", ReplyAction="http://tempuri.org/DBOperationsService/InsertABusResponse")]
        void InsertABus(BusOperationsClient_991396063.DBOperationServiceReference.BusInfo bus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBOperationsService/InsertABus", ReplyAction="http://tempuri.org/DBOperationsService/InsertABusResponse")]
        System.Threading.Tasks.Task InsertABusAsync(BusOperationsClient_991396063.DBOperationServiceReference.BusInfo bus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBOperationsService/RetrieveBusInfo", ReplyAction="http://tempuri.org/DBOperationsService/RetrieveBusInfoResponse")]
        BusOperationsClient_991396063.DBOperationServiceReference.BusInfo[] RetrieveBusInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBOperationsService/RetrieveBusInfo", ReplyAction="http://tempuri.org/DBOperationsService/RetrieveBusInfoResponse")]
        System.Threading.Tasks.Task<BusOperationsClient_991396063.DBOperationServiceReference.BusInfo[]> RetrieveBusInfoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DBOperationsServiceChannel : BusOperationsClient_991396063.DBOperationServiceReference.DBOperationsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DBOperationsServiceClient : System.ServiceModel.ClientBase<BusOperationsClient_991396063.DBOperationServiceReference.DBOperationsService>, BusOperationsClient_991396063.DBOperationServiceReference.DBOperationsService {
        
        public DBOperationsServiceClient() {
        }
        
        public DBOperationsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DBOperationsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBOperationsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBOperationsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InsertABus(BusOperationsClient_991396063.DBOperationServiceReference.BusInfo bus) {
            base.Channel.InsertABus(bus);
        }
        
        public System.Threading.Tasks.Task InsertABusAsync(BusOperationsClient_991396063.DBOperationServiceReference.BusInfo bus) {
            return base.Channel.InsertABusAsync(bus);
        }
        
        public BusOperationsClient_991396063.DBOperationServiceReference.BusInfo[] RetrieveBusInfo() {
            return base.Channel.RetrieveBusInfo();
        }
        
        public System.Threading.Tasks.Task<BusOperationsClient_991396063.DBOperationServiceReference.BusInfo[]> RetrieveBusInfoAsync() {
            return base.Channel.RetrieveBusInfoAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DBOperationServiceReference.AuthenticateUserService")]
    public interface AuthenticateUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthenticateUserService/AuthenticateUser", ReplyAction="http://tempuri.org/AuthenticateUserService/AuthenticateUserResponse")]
        string AuthenticateUser(string Name, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthenticateUserService/AuthenticateUser", ReplyAction="http://tempuri.org/AuthenticateUserService/AuthenticateUserResponse")]
        System.Threading.Tasks.Task<string> AuthenticateUserAsync(string Name, string Password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AuthenticateUserServiceChannel : BusOperationsClient_991396063.DBOperationServiceReference.AuthenticateUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthenticateUserServiceClient : System.ServiceModel.ClientBase<BusOperationsClient_991396063.DBOperationServiceReference.AuthenticateUserService>, BusOperationsClient_991396063.DBOperationServiceReference.AuthenticateUserService {
        
        public AuthenticateUserServiceClient() {
        }
        
        public AuthenticateUserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthenticateUserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticateUserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticateUserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AuthenticateUser(string Name, string Password) {
            return base.Channel.AuthenticateUser(Name, Password);
        }
        
        public System.Threading.Tasks.Task<string> AuthenticateUserAsync(string Name, string Password) {
            return base.Channel.AuthenticateUserAsync(Name, Password);
        }
    }
}
